create table CLIENTE 
( 
    CF         VARCHAR2(16)  not null 
        primary key, 
    PASSWORD_C VARCHAR2(32)  not null, 
    EMAIL      VARCHAR2(255) not null UNIQUE,
    DATA_REGISTRAZIONE DATE DEFAULT SYSDATE
);

create table RUBRICA_INDIRIZZI 
( 
    CF        VARCHAR2(16)  not null , 
    STATO     VARCHAR2(10)  not NULL 
        check (Stato IN ('attivo', 'inattivo')), 
    VIA       VARCHAR2(100)             not null, 
    CIVICO    VARCHAR2(6)               not null, 
    CAP       NUMBER(5)                 not null, 
    CITTA     VARCHAR2(100)             not null, 
    PROVINCIA VARCHAR2(4)               not null,
   CONSTRAINT FK_RUBRICA_CLIENTE FOREIGN KEY (CF) REFERENCES CLIENTE(CF)
);

create table DATI_ANAGRAFICI  
(  
    CF           VARCHAR2(16) not NULL UNIQUE,  
    NOME         VARCHAR2(50)  not null,  
    COGNOME      VARCHAR2(50)  not null,  
    DATAN        DATE          not null,  
    NUMERO_TEL_1 VARCHAR2(12)  not null,
   CONSTRAINT FK_DATI_ANAGRAFICI_CLIENTE FOREIGN KEY (CF) REFERENCES CLIENTE(CF)
);

create table BOX 
( 
    EAN_BOX         VARCHAR2(13) PRIMARY KEY, 
    NOME_BOX        VARCHAR2(255) NOT NULL, 
    CATEGORIA_BOX   VARCHAR2(255) DEFAULT NULL, 
    PORZIONI        NUMBER(1)     NOT NULL, 
    QUANTITA_IN_BOX NUMBER(3)     NOT NULL, 
    PREZZO_BOX      NUMBER(5, 2)  NOT NULL 
);

CREATE TABLE VALORI_NUTRIZIONALI (
    EAN_BOX  VARCHAR2(13) not null UNIQUE,
    PROTEINE NUMBER(5, 2) CHECK (PROTEINE >= 0) not null,
    CARBOIDRATI NUMBER(5, 2) CHECK (CARBOIDRATI >= 0) not null,
    ZUCCHERI NUMBER(5, 2) CHECK (ZUCCHERI >= 0) not null,
    FIBRE NUMBER(5, 2) CHECK (FIBRE >= 0) not null,
    GRASSI NUMBER(5, 2) CHECK (GRASSI >= 0) not null,
    SALE NUMBER(5, 2) CHECK (SALE >= 0) not null,
    CHILOCALORIE NUMBER(5) CHECK (CHILOCALORIE >= 0) not null,
    CONSTRAINT FK_VALORI_NUTRIZIONALI_BOX FOREIGN KEY (EAN_BOX) REFERENCES BOX(EAN_BOX)
);

create table ALLERGENI 
( 
    NOME_ALLERGENE        VARCHAR2(255) NOT NULL, 
    DESCRIZIONE_ALLERGENE VARCHAR2(255) DEFAULT NULL, 
    EAN_BOX   VARCHAR2(13)  NOT NULL, 
    CONSTRAINT FK_ALLERGENI_EAN_BOX FOREIGN KEY (EAN_BOX) REFERENCES BOX(EAN_BOX) 
);

create table MAGAZZINO 
( 
    NOME_MAGAZZINO VARCHAR2(20)
        constraint PK_MAGAZZINO 
            primary key, 
    VIA_MAG          VARCHAR2(100) not null, 
    CIVICO_MAG       VARCHAR2(6)   not null, 
    CAP_MAG VARCHAR2(10) CHECK (LENGTH(CAP_MAG) = 5) not null, 
    CITTA_MAG        VARCHAR2(100) not null, 
    PROVINCIA_MAG    VARCHAR2(4)   not null 
);

create table FORNITORE 
( 
    PARTITAIVA    VARCHAR2(11)  not null 
        constraint PK_FORNITORE 
            primary key, 
    NOME_FORNITORE    VARCHAR2(255) not null, 
    VIA_FOR       VARCHAR2(100) not NULL, 
    CIVICO_FOR    VARCHAR2(6)   not NULL, 
    CITTA_FOR     VARCHAR2(100) not NULL, 
    PROVINCIA_FOR VARCHAR2(4)   not NULL, 
    CAP_FOR VARCHAR2(10) CHECK (LENGTH(CAP_FOR) = 5) not null 
);

create table INGREDIENTE 
( 
    EAN_INGREDIENTE    VARCHAR2(13) not null 
        constraint PK_INGREDIENTE 
            primary key, 
    DESC_INGREDIENTE   VARCHAR2(255) default NULL, 
    NOME_INGREDIENTE   VARCHAR2(255) not NULL, 
    PREZZO_INGREDIENTE NUMBER(5, 2)  not NULL, 
    PARTITAIVA         VARCHAR2(11)  not NULL, 
     CONSTRAINT FK_INGREDIENTE  FOREIGN KEY (PARTITAIVA) REFERENCES FORNITORE(PARTITAIVA) 
);

CREATE TABLE INGREDIENTE_MAGAZZINO (
    DATA_INGRESSO DATE DEFAULT NULL,
    LOTTO VARCHAR2(10) DEFAULT NULL,
    QUANTITA_INGREDIENTE NUMBER(5) NOT NULL,
    EAN_INGREDIENTE VARCHAR2(13) NOT NULL,
    NOME_MAG VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_INGREDIENTE_MAG_EAN_INGREDIENTE FOREIGN KEY (EAN_INGREDIENTE) REFERENCES INGREDIENTE(EAN_INGREDIENTE),
    CONSTRAINT FK_INGREDIENTE_MAG_NOME_MAG FOREIGN KEY (NOME_MAG) REFERENCES MAGAZZINO(NOME_MAGAZZINO),
    CONSTRAINT PK_INGREDIENTE_MAGAZZINO PRIMARY KEY (EAN_INGREDIENTE, NOME_MAG)  -- Chiave primaria composta
);

CREATE TABLE COMPOSIZIONE_BOX (
    EAN_BOX VARCHAR2(13) NOT NULL,
    EAN_INGREDIENTE VARCHAR2(13) NOT NULL,
    CONSTRAINT FK_COMP_EAN_BOX FOREIGN KEY (EAN_BOX) REFERENCES BOX(EAN_BOX),
    CONSTRAINT FK_COMP_EAN_INGREDIENTE FOREIGN KEY (EAN_INGREDIENTE) REFERENCES INGREDIENTE(EAN_INGREDIENTE),
    CONSTRAINT PK_COMPOSIZIONE_BOX PRIMARY KEY (EAN_BOX, EAN_INGREDIENTE)  -- Chiave primaria composta
);


CREATE TABLE CARRELLO (
    CF                         VARCHAR2(16)   NOT NULL,  -- Codice Fiscale del cliente
    EAN_BOX                    VARCHAR2(13)   NOT NULL,  -- Codice del prodotto
    QUANTITA_IN_CARRELLO       NUMBER(3)      NOT NULL,  -- Quantità del prodotto
    PREZZO_BOX_UNITARIO_CARRELLO NUMBER(5, 2) NOT NULL,  -- Prezzo unitario del prodotto
    CONSTRAINT FK_CARRELLO_CF  FOREIGN KEY (CF) REFERENCES CLIENTE(CF),
    CONSTRAINT FK_CARRELLO_EAN_BOX FOREIGN KEY (EAN_BOX) REFERENCES BOX(EAN_BOX),
    CONSTRAINT PK_CARRELLO PRIMARY KEY (CF, EAN_BOX)  -- Chiave primaria composta da CF e EAN_BOX
);

CREATE TABLE SCONTI 
( 
    ID_SCONTO     NUMBER(11) 
        CONSTRAINT PK_SCONTI 
            PRIMARY KEY, 
    VALORE        NUMBER(3) not NULL, 
    INIZIO_SCONTO DATE       not NULL, 
    FINESCONTO    DATE       not NULL,
    CONSTRAINT CHK_DATE_SCONTI 
        CHECK (INIZIO_SCONTO < FINESCONTO)
);

create table ORDINE 
( 
    ID_ORDINE       VARCHAR2(30)
		constraint PK_ORDINE 
			primary key, 
    DATA_ORDINE     DATE         default NULL, 
    TOTALE_PREZZO   NUMBER(5, 2) not null, 
    TOTALE_QUANTITA NUMBER(2)    not null, 
    STATO_ORDINE    NUMBER(1)    default NULL check (Stato_ordine IN (1, 2, 3, 4)), 
    CF   VARCHAR2(16) NOT NULL, 
    CONSTRAINT FK_ID_ORDINE_ORDINE  FOREIGN KEY (CF) REFERENCES CLIENTE(CF), 
    ID_SCONTO       NUMBER(11)   NOT NULL,
    CONSTRAINT FK_ORDINE_ID_SCONTO  FOREIGN KEY (ID_SCONTO ) REFERENCES SCONTI(ID_SCONTO )
);

CREATE TABLE DETTAGLI_ORDINE (
    ID_ORDINE VARCHAR2(30) NOT NULL,
    EAN_BOX VARCHAR2(13) NOT NULL,
    QUANTITA_BOX_DETTAGLI NUMBER(2) NOT NULL,
    PREZZO_BOX_DETTAGLI NUMBER(4, 2) NOT NULL,
    CONSTRAINT FK_DETTAGLI_ORDINE_ID_ORDINE FOREIGN KEY (ID_ORDINE) REFERENCES ORDINE(ID_ORDINE),
    CONSTRAINT FK_DETTAGLI_ORDINE_EAN_BOX FOREIGN KEY (EAN_BOX) REFERENCES BOX(EAN_BOX),
    CONSTRAINT PK_DETTAGLI_ORDINE PRIMARY KEY (ID_ORDINE, EAN_BOX)  -- Chiave primaria composta
);



create table FATTURA 
( 
    METODO_PAGAMENTO VARCHAR2(50)  default NULL, 
    DATA_PAGAMENTO   DATE          default NULL, 
    IMPORTO          NUMBER(10, 2) default NULL, 
    ID_ORDINE        VARCHAR2(30)   not NULL UNIQUE,
    CONSTRAINT FK_FATTURA_ID_ORDINE FOREIGN KEY (ID_ORDINE) REFERENCES ORDINE(ID_ORDINE)
);

create table SPEDIZIONE 
(  
    CORRIERE         VARCHAR2(100) not NULL, 
    STATO_SPEDIZIONE VARCHAR2(10)  not NULL check (Stato_spedizione IN ('1', '2', '3','4')), -- 1 in lavorazione , 2 spedito , 3 consegnato, 4 cancellata 
    ID_ORDINE        VARCHAR2(30)    not NULL UNIQUE,
    CONSTRAINT FK_SPEDIZIONE_ID_ORDINE FOREIGN KEY (ID_ORDINE) REFERENCES ORDINE(ID_ORDINE), 
    VIA_SPEDIZIONE                 VARCHAR2(100) not null, 
    CIVICO_SPEDIZIONE           VARCHAR2(6)   not null, 
    CAP_SPEDIZIONE                NUMBER(5)     not null, 
    CITTA_SPEDIZIONE             VARCHAR2(100) not null, 
    PROVINCIA_SPEDIZIONE    VARCHAR2(4)   not null 
);